### ISSUE TITLE
'JQuery<HTMLElement>' 형식에 'postcodify' 속성이 없습니다.

### ISSUE THREAD

**Issue by thswnsdud456** [poesis/postcodify#16]
Angular 에서도 사용가능하네요!!

하지만 'JQuery<HTMLElement>' 형식에 'postcodify' 속성이 없습니다.  이 에러를 어떻게 처리하면 좋을까요?
![image](https://user-images.githubusercontent.com/54301605/104686936-96d58b00-5741-11eb-9439-c47562193edb.png)
![image](https://user-images.githubusercontent.com/54301605/104689359-bd95c080-5745-11eb-867e-6473042b9af4.png)

**Comment by kijin** [comment]
https://www.google.com/search?q=angular+jquery+plugin+property+does+not+exist+on+type+jquery
